- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: importing variables
      include_vars: Vpc_Variables

    - name: create vprofile vpc
      ec2_vpc_net:
       name: "{{VpcName}}"
       cidr_block: "{{VPCCidr}}"
       dns_support: true
       dns_hostnames: true
       region: "{{Region}}"
       state: "{{state}}"
      register: vpcout

    - debug:
       var: vpcout

    - name: Creating VPC subnets
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{Region}}"
        state:  "{{state}}"
        az: "{{Zone1}}"
        cidr: "{{pubsubCIDR1}}"
        map_public: true
        resource_tags:
          Name: FirstSubnet
      register: pubsubpout


      
