- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: importing variables
      include_vars: Vars/vpc_setup.txt

    - name: create vprofile vpc
      ec2_vpc_net:
       name: "{{Ansible_vpc}}"
       cidr_blocks: "{{VPCCidr}}"
       tenacy: "default"
       dns_support: true
       dns_hostnames: true
       region: "{{Region}}"
       state: "{{state}}"
      register: vpcout

