- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: importing variables
      include_vars: Vpc_Variables

    - name: create vprofile vpc
      ec2_vpc_net:
       name: "{{VpcName}}"
       cidr_block: "{{VPCCidr}}"
       dns_support: true
       dns_hostnames: true
       region: "{{Region}}"
       state: "{{state}}"
      register: vpcout

    - debug:
       var: vpcout

    - name: Creating VPC subnets
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{Region}}"
        state:  "{{state}}"
        az: "{{Zone1}}"
        cidr: "{{pubsubCIDR1}}"
        map_public: true
        resource_tags:
          Name: FirstSubnet
      register: pubsubpout1

    - name: Creating VPC subnet2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{Region}}"
        state:  "{{state}}"
        az: "{{Zone2}}"
        cidr: "{{pubsubCIDR2}}"
        map_public: true
        resource_tags:
          Name: 2ndSubnet
      register: pubsubpout2

    - name: Creating VPC private subnet3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{Region}}"
        state:  "{{state}}"
        az: "{{Zone3}}"
        cidr: "{{PriSubCidr3}}"
        map_public: true
        resource_tags:
          Name: 3rdprivateSubnet
      register: privatesubpout3

    - name: Creating VPC private subnet2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{Region}}"
        state:  "{{state}}"
        az: "{{Zone3}}"
        cidr: "{{pubsubCIDR3}}"
        map_public: true
        resource_tags:
          Name: 3rdSubnet
      register: pubsubpout3

    - name: Creating VPC Private subnets23
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{Region}}"
        state:  "{{state}}"
        az: "{{Zone1}}"
        cidr: "{{PriSubCidr1}}"
        map_public: true
        resource_tags:
          Name: FirstPriSubnet
      register: prisubpout

    - name: Creating VPC subnets
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{Region}}"
        state:  "{{state}}"
        az: "{{Zone2}}"
        cidr: "{{PriSubCidr2}}"
        map_public: true
        resource_tags:
          Name: 2ndprivSubnet
      register: privsubpout2
      
    - name: Internet gateway Setup
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{Region}}"
        tags:
          tag1: Ansible_vpc_IGW

      register: igw

    - name: Route Table for IGW
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{Region}}"
        tags:
          name: Vprofile pubRoutTable
        subnets:
          - "{{pubsubpout1.subnet.id}}"
          - "{{pubsubpout2.subnet.id}}"
          - "{{pubsubpout3.subnet.id}}"
        routes:
         - dest: 0.0.0.0/0
           gateway_id: "{{igw.gateway_id}}"
      register: Ansible_IGW_RouteTable

    - debug:

       var: Ansible_IGW_RouteTable